### ISSUE TITLE
Would you like to add this repository to CAP's official documentation

### ISSUE THREAD

**Issue by yang-xiaodong** [cocosip/CAP-Extensions#1]
Hello there,

I saw this place. It can be added to the official CAP document as an extension implemented by the community, so that other people can find it here through the document. If you want, you can submit a PR to modify the [docs](https://github.com/dotnetcore/CAP/blob/master/docs/content/user-guide/zh/storage/general.md#%E7%A4%BE%E5%8C%BA%E6%94%AF%E6%8C%81%E7%9A%84%E6%8C%81%E4%B9%85%E5%8C%96).

Thanks

**Comment by cocosip** [comment]
> Hello there,
> 
> I saw this place. It can be added to the official CAP document as an extension implemented by the community, so that other people can find it here through the document. If you want, you can submit a PR to modify the [docs](https://github.com/dotnetcore/CAP/blob/master/docs/content/user-guide/zh/storage/general.md#%E7%A4%BE%E5%8C%BA%E6%94%AF%E6%8C%81%E7%9A%84%E6%8C%81%E4%B9%85%E5%8C%96).
> 
> Thanks

I have modify the docs  and submit a PR , https://github.com/dotnetcore/CAP/pull/661   :smile:

**Comment by yang-xiaodong** [comment]
Nice
